### ISSUE TITLE
西尔里文的问题

### ISSUE THREAD

**Issue by toolor** [ethantw/Han#111]
请问，支持俄罗斯文吗？我的博客中文，俄罗斯文混写的，

**Comment by ethantw** [comment]
可以的，較重要的功能如「著重號」及「漢字－西文混排間隙」皆支援與西里爾字母的混用，您可以參考下面的範例。

- http://ethantw.github.io/Han/latest/em.html
- http://ethantw.github.io/Han/latest/hws.html

如果使用上遇到具體的問題，歡迎另行提出。
