### ISSUE TITLE
hanging-punctuation 效果如何实现

### ISSUE THREAD

**Issue by MrXCQ** [ethantw/Han#115]
hanging-punctuation
![图片](https://user-images.githubusercontent.com/15794342/76388981-51b82e00-63a5-11ea-9edc-e36d4d457ec4.png)
支持上述效果吗？能不能告知一下方法，多谢

**Comment by weakish** [comment]
支持标点悬挂（hanging-punctuation），用法见[文档][doc]。

[doc]: https://hanzi.pro/manual/hang_de_zucheng#hangwei_dianhao_xuangua

实现方法陈奕钧在[内核恐慌第 16 期][16]结尾(1:33:40-1:37:00)介绍过，是一个非常巧妙的 hack。因为行尾的半角空格会被浏览器的排版引擎挤出去，所以将可以悬挂的标点符号都替换为半角空格，再搭配专门制作的 web font 将半角空格显示为一个汉字（全角标点符号）的大小，最后将原来的标点叠加上去，这样就实现了标点悬挂（也就是利用浏览器对空格的处理机制给可悬挂的标点定位）。
