### ISSUE TITLE
标点悬挂在 Chrome 85 (Mac) 里出现错误

### ISSUE THREAD

**Issue by realfish** [ethantw/Han#116]
<img width="1246" alt="snapshot" src="https://user-images.githubusercontent.com/3247876/94172272-df341900-fec4-11ea-94f1-d2641889a505.png">

上图是[测试页面](https://ethantw.github.io/Han/latest/hanging.html)在 Chrome 85.0.4183.121 (Mac) 里的呈现。标点悬挂（好像部分地？）出了问题——比如截图的范围内，最后一行「我认为，没人可以「如此」放肆，」的逗号悬挂正常，但其他行尾悬挂标点都进入了下一行、并与行头字符重叠。

macOS 同时期版本的 Safari 和 Firefox 没有问题。

**Comment by ethantw** [comment]
在Version 89.0.4389.82中已經沒有這個問題，先關咯 ^_^a

<img width="803" alt="Screenshot 2021-03-07 at 22 43 39" src="https://user-images.githubusercontent.com/31068/110243747-ad0c0480-7f96-11eb-97b4-0fddc155426e.png">
