### ISSUE TITLE
Follow CLREQ(Requirements for Chinese Text Layout)

### ISSUE THREAD

**Issue by FradSer** [ethantw/Han#117]
[CLREQ](https://w3c.github.io/clreq/) is now working draft, I think if Han follow it should be a very nice collaboration.
Like [3.1.6.1 Punctuation Adjustment Space](https://w3c.github.io/clreq/#punctuation_width_adjustment), "in order to make the the composition tighter and more readable," ... "the width of the punctuation marks needs to be adjusted."

**Comment by caasi** [comment]
@ethantw is already a CLREQ contributor.

see: https://github.com/w3c/clreq/commits/gh-pages?after=b39d446914767b8d2764c6c6893f301f0989c855+139&branch=gh-pages

**Comment by FradSer** [comment]
Maybe some new feature will ship?
