### ISSUE TITLE
Please tag 3.1.0

### ISSUE THREAD

**Issue by int64ago** [ethantw/Han#70]
So cdnjs can autoupdate, thx

**Comment by ethantw** [comment]
v3.1.0 isn't ready for release right now. Please use v3.0.2 for now. Sorry for the inconvenience.

**Comment by int64ago** [comment]
But the README may confuse other guys

**Comment by ethantw** [comment]
Yes, thanks for the heads-up. I've just updated the files back to the previous version.

**Comment by ethantw** [comment]
Published v3.1.0. Waiting for NPM to update the new version and cdnjs to cache. :smiley:
