### ISSUE TITLE
使用手册的错误

### ISSUE THREAD

**Issue by xiashali** [ethantw/Han#75]
http://css.hanzi.co/manual
在简体下，右下角「协助妥善这分文件」中的这分—这份

**Comment by ethantw** [comment]
見：
- <https://www.moedict.tw/分>
- <http://www.zdic.net/z/15/js/5206.htm>

如果遇到使用手冊的問題，可以透過「协助妥善这分文件」按鈕，在[Han-Manual](https://github.ocm/ethantw/Han-Manual)專案中提報、發PR。感謝。 :smile_cat:
