### ISSUE TITLE
國標中，彎引號與其他標點共同出現時沒有壓縮間距。

### ISSUE THREAD

**Issue by dangfan** [ethantw/Han#77]
點號與彎引號之間的空白應該壓縮

**Comment by ethantw** [comment]
你好，這其實是intentional的設計。由於中文與西文共用彎引號的碼位，具體難自代碼層面得知一個彎引號屬於中文或西文，故刻意繞開其標點擠壓的處理。

具體請見這個討論：https://github.com/ethantw/Han/issues/48

若有需要，建議你改用「Biaodian Pro Sans」「Biaodian Pro Serif」等*類似*中國國家標準的標點字體（可以在Sass中以變數調整）。字體正常回退的情況下，彎引號將使用西文比例字體（而非漢字等寬字體）顯示。
