### ISSUE TITLE
Bootstrap、Font Awesome 衝突

### ISSUE THREAD

**Issue by fadequ** [ethantw/Han#80]
跟 Bootstrap、Font Awesome 有衝突，找到常見問題裡「樣式的覆蓋」不是很懂，也搜索不到教程，望作者能否出一個在 Bootstrap 中使用 han.css 的簡易說明，感謝🙏

**Comment by ethantw** [comment]
你好。

關於Font Awesome圖標字體與Han.css相衝突的問題，建議你改用我開發的[Font Handsome](https://github.com/ethantw/font-handsome)，這個專案支援所有Font Awesome的圖標，可以在樣式表（預處理器）層面套用，目前支援Sass及Stylus。[Han.css官網](https://css.hanzi.co/)即使用此專案。

我並未深入研究過Bootstrap，且Bootstrap項目比較龐大，能否請你留下問題網頁或用[JS Bin](http://jsbin.com)把問題樣式展示出來，我可以幫你檢査看看。

**Comment by fadequ** [comment]
你好 @ethantw 

與 Font Awesome 衝突的問題往後就用你的 Font Handsome 好了，剛把網頁貼到了 JS Bin http://jsbin.com/vigeto

HTML 第 13 行 han.css 現在已經註釋掉，非常感謝你的熱心幫助！

**Comment by ethantw** [comment]
具體有什麼問題嗎？我這邊看起來很正常哦

**Comment by fadequ** [comment]
@ethantw 啟用 bootstrap.css 後 han.css 就不工作，註釋掉 bootstrap.css 後你看 han.css 渲染的文字及中文標點修正 http://cl.ly/brO3

**Comment by ethantw** [comment]
在Bootstrap或Han.css後方加上這段樣式規則應該就行了，

```css
body {
  font-family: inherit;
}
```

**Comment by fadequ** [comment]
果然😂 哈哈太棒了，謝謝！@ethantw

**Comment by ethantw** [comment]
先關票，有問題歡迎再提出來 :smile_cat:

**Comment by fadequ** [comment]
真抱歉😀 又遇到問題了，還是與 Bootstrap 共用引起的。導入 han.js 後標點符號就偏移了還變成了灰色，請見截圖 http://cl.ly/brWK

移除 bootstrap.css 就恢復正常

**Comment by ethantw** [comment]
標點處理的類別「close」與BS的衝突。

如果不是長文頁面，其實不大需要引入han.js腳本。

**Comment by fadequ** [comment]
想用到中英文混排加入間隔的功能需要 JS，不過問題不大 :) 謝謝 @ethantw

**Comment by ethantw** [comment]
請按使用手冊的說明，另行制定需要的渲染方式，不要使用預設値即可。

**Comment by fadequ** [comment]
好的，我再研究研究😸
