### ISSUE TITLE
似乎不支持Material design icon

### ISSUE THREAD

**Issue by jingsam** [ethantw/Han#85]
引入han-css后，图标字体会变为文字

**Comment by ethantw** [comment]
你好，

- 若您使用`i`元素引用Material Design圖標，您可以：

  * 改用其他元素，如`span`等，因為漢字標準格式為`i`元素設定了相應的字體，且選擇器的優先層級較高，不建議在`i`元素上引入圖標； 
  * 或使用類似[font-handsome](//github.com/ethantw/font-handsome)框架的方式，在CSS預處理器層面引用圖標；
  * 改用inline svg引用圖標。

- 若您使用inline svg的方式引用Material Design的圖標且仍有問題，建議您將相關代碼以[JS Bin](http://jsbin.com)等工具調試後，提供連結，方便我們除錯，謝謝！
