### ISSUE TITLE
O.init is not a function

### ISSUE THREAD

**Issue by billy3321** [ethantw/Han#86]
不好意思，我製作了一個網頁，並引用了CDN上面的han.js。不過卻一直頻繁跳出錯誤。

錯誤訊息如下：

```
han.min.js:5
Uncaught TypeError: O.init is not a function(anonymous function)
```

我的網頁在[此](http://billy3321.github.io/request_xi_resign/)，希望可修正這個錯誤，感謝！

**Comment by ethantw** [comment]
你好，

您的網頁中，同時包含了 A）在`<html>`元素套用`han-init`類別及  B）在網頁底部的`<script>`中調用了`Han.init()`二種全頁渲染啓用機制。

根據使用手冊，han.js在完成預設的DOM ready全頁渲染後，會將`Han.init`命名空間替換為該Han實例[1]。此時Han.init已經不是函式，而是一個Han實例，造成上述錯誤。

請依需要，選用A或B一種啓用方式即可。如果還有問題，請再告知，謝謝！

\[1]: http://hanzi.pro/manual/js-api#Han-init-as-an-instance

**Comment by billy3321** [comment]
原來如此。感謝！
