### ISSUE TITLE
直角引號內最後一個句號自動消失

### ISSUE THREAD

**Issue by apm1467** [ethantw/Han#87]
`<p>「穿过。」</p>` 在頁面上會顯示為：

<img width="217" alt="screenshot of selection" src="https://cloud.githubusercontent.com/assets/10210967/14199134/041fba24-f7e2-11e5-875b-96430be8ed3f.png">

而 `<p>「穿过。」。</p>` 在頁面上則正常顯示為：

<img width="213" alt="screenshot of selection" src="https://cloud.githubusercontent.com/assets/10210967/14199160/45d24eb4-f7e2-11e5-9a37-59e5e1b98169.png">

不知是我操作不當，還是確實 bug？

**Comment by ethantw** [comment]
可以提供測試範例頁嗎？如jsBin等。我這邊測試沒有問題。

**Comment by apm1467** [comment]
例如這個：https://jsbin.com/copakadiwo/edit?html,output

在範例頁面上看一切正常，但我把 html 文件下載到本地，在 OS X 10.11.4 上使用 Safari 打開，重現了問題。

**Comment by ethantw** [comment]
見：https://github.com/ethantw/Han/issues/86

TL;DR：有了`<html class="han-init">`就不需要再`Han( xxx ).render()`一次咯。

v.3.3.0版本對第二次渲染做了比較嚴謹的處理，所以不會有這個問題。

**Comment by apm1467** [comment]
好像發現問題了。申明字體時在後面加一個 !important 就一切正常。

`body {
      font-family: 'Biaodian Pro Serif CNS', serif !important;
 }`

**Comment by apm1467** [comment]
明白了，是我文檔沒看懂……非常感謝！

**Comment by ethantw** [comment]
> 好像發現問題了。申明字體時在後面加一個 !important 就一切正常。

跟那個關係不大，主要是一個document.body渲染了二次。

若您在簡體中文網頁中，選用「台灣教育部式的標點字體」，建議不要使用預設的渲染途徑，應把`.renderHanging()`關閉。

PS：jsBin上的外連樣式表及腳本都沒有正確加載（協議不同），所以完全沒看到效果及重現……請用README建議的寫法：

```html
<link rel="stylesheet" media="all" href="//cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.js"></script>
```

**Comment by apm1467** [comment]
如果使用 README 建議的寫法，CSS 和 JS 在 OS X 上 Safari 都會無法加載，導致完全沒有效果，加了 http 后就不會，我是測試后被迫加上的。

![screenshot of window](https://cloud.githubusercontent.com/assets/10210967/14200822/e68a4360-f7ed-11e5-80d6-664fb1aada87.png)
