### ISSUE TITLE
Getting han.js modularized

### ISSUE THREAD

**Issue by laosb** [ethantw/Han#92]
这个项目中，han.js 效果出众，但是整个 js 依赖浏览器环境，而且事实上只支持每个页面一个渲染区。想问问有没有计划让它做到：

1. 遵循 ES6 标准的模块化支持
2. 去除浏览器依赖
3. 不影响渲染区外的 DOM 元素（如 `body`），使得一个页面中能容纳多个渲染区及多次重渲染，支持 SPA
4. 支持主流 view 框架，如 Vue、React等，最好能够直接提供相关 component

希望能得到回复。

PS：我们在 [Immortal.Work](https://immortal.work) 中使用了这个项目的成果，但是用得并不是很爽。相信这些问题不少用户也遇到了，所以就权且在这里提出来。

**Comment by ethantw** [comment]
您好！謝謝關注並使用漢字標準格式這個項目。

首先回答後二個問題，其實現在一個頁面並非只有一個渲染區域，只是為了方便快速啓用，提供了`.han-init`這個自動渲染的方法。但你可以在任何新的DOM元素進入頁面後，透過`Han( element ).render()`方法來重新渲染頁面 \[1]。在React中，可以在組件的`componentDidMount`和`componentDidUpdate`階段用`Han()`來渲染組件。

 \[1]: https://hanzi.pro/manual/anzhuang_yu_qiyong#sec-9

其實早在去年年底時便開始進行以ES6改寫和伺服器端渲染的計畫，但我個人一直沒有時間收尾，所以項目便一直拖著。目前工作已經基本完成，但依賴的底層庫實現效率不佳，還有很多workaround待改進。感與趣的話請參考：

1. https://github.com/ethantw/hanio
2. https://github.com/ethantw/fibrio

**Comment by laosb** [comment]
目测渲染的时候会修改 `body` 及 `html` 的 class，而且 css 上也是全页面的。我想能不能在 css 上做成非侵入的呢？

**Comment by ethantw** [comment]
`body`應該沒有加額外的class。

加在`html`上的classes並不直接承載樣式，而是在CSS中做為條件判斷、為不同支援情況的系統或瀏覽器套用不同的樣式規則，這些classes加在`html`元素上是比較方便，且基本上不影響頁面。

你可以自行編譯Stylus或Sass原碼，把需要限定範圍的樣式包裹在一個（或多個）選擇器範圍中即可。

**Comment by laosb** [comment]
目测所有的字体都被 han.css 带跑了：

![image](https://cloud.githubusercontent.com/assets/2545261/21576457/4032cb94-cf6b-11e6-9f26-ebc9d25a0b67.png)

大多数情况下，我并不希望全页套用这个字体，仅在指定范围内使用是多数情况下的需求。希望在这方面能提供更方便的方式而不是要求用户自己编译 sass/stylus。

**Comment by ethantw** [comment]
> 大多数情况下，我并不希望全页套用这个字体，仅在指定范围内使用是多数情况下的需求。希望在这方面能提供更方便的方式而不是要求用户自己编译 sass/stylus。

這個需求非常合理，而框架最初設計時便為使用者提供了最大的彈性——根據自己的需要，自行決定要引入哪些樣式模塊（或以開放的變量來設定）。**若完全沒有自定義的需求**，漢字標準格式提供了預先編譯好的CSS文件，方便快速上手啓用。可能您對這分預先編譯的CSS文件的本意有所誤解，才做此想。

> One possible solution: 提供一个独立的特殊版本的 han.css，仅对某一特定 class 内的元素应用 han.css 样式。

漢字標準格式遵循「語意網」的要求，最大程度地避免使用「展示性類別」（presentational classes，經由腳本判斷添加者除外），所以不太可能採用這種方式。而考慮到您提出的「僅在指定範圍內使用漢字標準格式提供的字體回退」這個需求可能較廣泛，我會在下個版本中，在預處理器加入相應的開關及選擇器設定變量，初步的構想為：

```stylus
$han-typography = true
$han-typography-context = main.content
```

如此一來，漢字標準格式提供的字體回退便只作用於符合`main.content`選擇器的元素上。

有其他建議也歡迎提出。
