### ISSUE TITLE
`dist` should be ignored on `.gitignore`

### ISSUE THREAD

**Issue by JLHwung** [ethantw/Han#94]
The built library should be excluded from the source repository for a reasonable repository history. 
Ideally we should run [git-filter-branch](https://git-scm.com/docs/git-filter-branch) to delete all the history of `dist` but simple deletion will be also acceptable if many dev branched outstands.
 
Adding build process to `prepublishOnly` will ensure end user got `dist` included in the npm package.

**Comment by ethantw** [comment]
OK, looks like something worth doing. I’ll dig into it later. :smith

**Comment by JLHwung** [comment]
Hi ethantw,

This issue is open as discussion on src/build separation. If we agree on the plan I can work on a PR later.

**Comment by ethantw** [comment]
> This issue is open as discussion on src/build separation. If we agree on the plan I can work on a PR later.

Yeah, a PR would be nice. Thanks!

**Comment by ethantw** [comment]
Done! Thanks again!

**Comment by JLHwung** [comment]
You are very welcome.
