### ISSUE TITLE
Conflict With Font-awesome CSS

### ISSUE THREAD

**Issue by Yogayu** [ethantw/Han#97]
When I use the han CSS and the font-awesome CSS, the icons can't be seen.
Like:

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/Han/3.2.7/han.min.css"/>

The icons will look like this:
![image](https://cloud.githubusercontent.com/assets/10155763/23643333/0c3183bc-033c-11e7-99d0-be9d625d295e.png)

**Comment by ethantw** [comment]
Please do not use `<i>` elements for icons. It is not only ugly but against the principal of semantic web.

A good substitution to Font Awesome CSS is [Font Handsome](https://github.com/ethantw/font-handsome).

**Comment by Yogayu** [comment]
Thx.
