### ISSUE TITLE
在<a>中禁用相邻文本装饰线跳脱

### ISSUE THREAD

**Issue by laosb** [ethantw/Han#98]
一般来讲，超链接采用下划线是一种常规样式。这在应用了 han.css 的页面上会表现不佳：

![image](https://cloud.githubusercontent.com/assets/2545261/23836498/6fc7b410-07b4-11e7-976f-2cdf840875a7.png)

我们希望链接中能够将整个`<a>`中的下划线连接起来。

**Comment by ethantw** [comment]
謝謝提報。這應該是「漢字西文混排間隙」造成的，我再想想有沒有解決方法。

**Comment by ethantw** [comment]
修復後的效果： 

<img width="334" alt="screen shot 2017-04-24 at 01 03 01" src="https://cloud.githubusercontent.com/assets/31068/25315577/d019437e-2889-11e7-83a3-35e658241b53.png">

修復後，漢字−西文混排間隙不再是四分之一個漢字的寬度，其大小依字體的空白字符（U+0020）而定。未來有機會再試著調整這個部分。

**Comment by laosb** [comment]
感谢！
